name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest


    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Verify files (optional)
      - name: List project files
        run: ls -R

      # Step 4: Install dependencies using clean install
      - name: Install dependencies
        run: npm ci

      # Step 5: Run tests
      - name: Run tests
        run: npm test 

      
